# INTRO TO JUPYTER NOTEBOOK

In [ ]:
# 1. CMD
# 2. jupyter notebook > this service/ window should always be running
# 3. default location > http://localhost:8888/tree
# 4. / means C:\ is root Folder
# 5. Create a new Python file

Press Esc to ensure you're in command mode (the cell border will turn blue), then press A to insert a cell above or B to insert a cell below the current cell.

M for Markdown cells or Y for code cells.

ctrl + enter to run cell

# INTRO TO NUMPY

In [ ]:
#  https://numpy.org/doc/stable/user/quickstart.html#an-example

# WHY NUMPY?

In [4]:
a1 = [1,2,3,4,5,6,7,8,9]
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
# to double the elements in list a1
for i in a1:
    print(i*2)

2
4
6
8
10
12
14
16
18


In [9]:
a2 = [i*2 for i in a1] 
# list comprehension
print(a2)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
# to square the element in the list a1

In [13]:
print(a1)
for i in a1:
    print(i**2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
1
4
9
16
25
36
49
64
81


In [14]:
a3=[i**2 for i in a1]
print(a3)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


# better approach??

In [ ]:
import numpy as np

In [17]:
print('hello world')

hello world


In [18]:
name = 'Rakesh'
print(name.casefold())

rakesh


In [20]:
arr1 = np.array(a1)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [21]:
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [27]:
print(a1*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
print(arr1*2)
# numpy supports elementwise operation

[ 2  4  6  8 10 12 14 16 18]


In [31]:
print(arr1**3)

[  1   8  27  64 125 216 343 512 729]
