# revision

In [1]:
a1 = [11,22,33,4,55]
print(a1)
print(type(a1))

[11, 22, 33, 4, 55]
<class 'list'>


In [3]:
import numpy as np

In [4]:
arr1 = np.array(a1)
# converting list into array
print(arr1)

[11 22 33  4 55]


In [6]:
# typecasting example from python basics
num=100
x=str(num)
print(x)
print(type(x))

100
<class 'str'>


In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


# elementwise operation

In [8]:
for i in a1:
    print(i*2)

22
44
66
8
110


In [10]:
a2 =[i*2 for i in a1]
print(a2)

[22, 44, 66, 8, 110]


In [11]:
arr1*2

array([ 22,  44,  66,   8, 110])

In [12]:
arr1**2

array([ 121,  484, 1089,   16, 3025])

In [13]:
arr1*arr1

array([ 121,  484, 1089,   16, 3025])

In [14]:
arr1+arr1

array([ 22,  44,  66,   8, 110])

In [16]:
arr1*arr1*arr1

array([  1331,  10648,  35937,     64, 166375])

In [18]:
arr1**3

array([  1331,  10648,  35937,     64, 166375], dtype=int32)

In [19]:
arr1

array([11, 22, 33,  4, 55])

In [20]:
arr2 = np.array([1,2,3])
print(arr2)

[1 2 3]


In [21]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 