# faster operations

In [1]:
import numpy as np

In [5]:
a1 = list(range(50))
print(a1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [6]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [15]:
%timeit [i*i for i in a1]

1.8 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
%timeit [i*i for i in a1]

1.82 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
a2 = np.arange(50)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [19]:
%timeit [a2*a2]

494 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array Attributes

In [21]:
a3 = [10,20,30,40]

In [22]:
a4 = np.array(a3)

In [23]:
a4

array([10, 20, 30, 40])

In [24]:
a4.shape

(4,)

In [25]:
a4.size

4

In [26]:
a4.ndim

1

# 1D Array Creation

In [ ]:
# By passing a list
# arange()
# using linspace() : will create the number of elements required between two points (start value:end value-1:no.of elements)

In [ ]:
# By passing a list

In [29]:
a5 = [0,1,2,3,4,5,6,7,8,9]
print(type(a5))
a6 = list(range(25))
print(a6)

arr1 = np.array(a6)
print(arr1)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [31]:
arr1.shape

(25,)

In [32]:
arr1.size

25

In [33]:
arr1.ndim

1

In [ ]:
# arange()

In [35]:
arr2 = np.arange(10)
arr2
# print(arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2.shape

(10,)

In [37]:
arr2.size

10

In [38]:
arr2.ndim

1

In [41]:
a7 = list(range(7,85,3))
arr7 = np.array(a7)
print(a7)
print(arr7)
arr7.size

[7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82]
[ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76
 79 82]


26

In [ ]:
# using linspace()

In [44]:
arr8 = np.linspace(1,10,5)
arr8
# print(arr8)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# arange and linspace difference

In [45]:
arr8 = np.arange(1,10,5)
arr8

array([1, 6])

In [48]:
arr8 = np.linspace(1,2,100)
arr8

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [49]:
arr8 = np.arange(1,2,100)
arr8

array([1])

In [ ]:


using negative side

In [51]:
arr8 = np.linspace(1,-2,100)
arr8

array([ 1.        ,  0.96969697,  0.93939394,  0.90909091,  0.87878788,
        0.84848485,  0.81818182,  0.78787879,  0.75757576,  0.72727273,
        0.6969697 ,  0.66666667,  0.63636364,  0.60606061,  0.57575758,
        0.54545455,  0.51515152,  0.48484848,  0.45454545,  0.42424242,
        0.39393939,  0.36363636,  0.33333333,  0.3030303 ,  0.27272727,
        0.24242424,  0.21212121,  0.18181818,  0.15151515,  0.12121212,
        0.09090909,  0.06060606,  0.03030303,  0.        , -0.03030303,
       -0.06060606, -0.09090909, -0.12121212, -0.15151515, -0.18181818,
       -0.21212121, -0.24242424, -0.27272727, -0.3030303 , -0.33333333,
       -0.36363636, -0.39393939, -0.42424242, -0.45454545, -0.48484848,
       -0.51515152, -0.54545455, -0.57575758, -0.60606061, -0.63636364,
       -0.66666667, -0.6969697 , -0.72727273, -0.75757576, -0.78787879,
       -0.81818182, -0.84848485, -0.87878788, -0.90909091, -0.93939394,
       -0.96969697, -1.        , -1.03030303, -1.06060606, -1.09

In [54]:
arr8 = np.linspace(2,-1,100)
arr8

array([ 2.        ,  1.96969697,  1.93939394,  1.90909091,  1.87878788,
        1.84848485,  1.81818182,  1.78787879,  1.75757576,  1.72727273,
        1.6969697 ,  1.66666667,  1.63636364,  1.60606061,  1.57575758,
        1.54545455,  1.51515152,  1.48484848,  1.45454545,  1.42424242,
        1.39393939,  1.36363636,  1.33333333,  1.3030303 ,  1.27272727,
        1.24242424,  1.21212121,  1.18181818,  1.15151515,  1.12121212,
        1.09090909,  1.06060606,  1.03030303,  1.        ,  0.96969697,
        0.93939394,  0.90909091,  0.87878788,  0.84848485,  0.81818182,
        0.78787879,  0.75757576,  0.72727273,  0.6969697 ,  0.66666667,
        0.63636364,  0.60606061,  0.57575758,  0.54545455,  0.51515152,
        0.48484848,  0.45454545,  0.42424242,  0.39393939,  0.36363636,
        0.33333333,  0.3030303 ,  0.27272727,  0.24242424,  0.21212121,
        0.18181818,  0.15151515,  0.12121212,  0.09090909,  0.06060606,
        0.03030303,  0.        , -0.03030303, -0.06060606, -0.09