## more on 2D arrays

In [1]:
import numpy as np

In [2]:
# arange() vs linspace()

In [4]:
arr1 = np.array([11,22,33])
arr1

array([11, 22, 33])

In [5]:
arr2 = np.arange(1,50,17)
arr2

array([ 1, 18, 35])

In [6]:
arr3 = np.linspace(1,50,17)
arr3

array([ 1.    ,  4.0625,  7.125 , 10.1875, 13.25  , 16.3125, 19.375 ,
       22.4375, 25.5   , 28.5625, 31.625 , 34.6875, 37.75  , 40.8125,
       43.875 , 46.9375, 50.    ])

In [7]:
# reshaping

In [8]:
arr4 = np.linspace(1,12,12)
print(arr4)
print(type(arr4))
print(arr4.ndim)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
<class 'numpy.ndarray'>
1


In [9]:
arr5 = arr4.reshape(3,4)
print(arr5)
print(arr5.ndim)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
2


# row vector and column vector

In [12]:
arr6 = np.arange(6).reshape(1,6) 
# row vector
arr6

array([[0, 1, 2, 3, 4, 5]])

In [13]:
arr7 = np.arange(6).reshape(6,1)
# column vector
arr7

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Dealing with wrong parameter

In [14]:
arr8 = np.arange(18).reshape(6,3)
arr8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
arr9 = np.arange(18).reshape(6,-8)
# wrong parameter will be recalculated by numpy and autocorrect
arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [18]:
arr10 = np.arange(18).reshape(6,9)
# wrong parameter i.e only unvalid parameter will be recalculated by numpy ,autocorrect
arr10

ValueError: cannot reshape array of size 18 into shape (6,9)

In [19]:
arr1 = np.arange(18).reshape(6,0)
# wrong parameter i.e only unvalid parameter will be recalculated by numpy ,autocorrect
arr11

ValueError: cannot reshape array of size 18 into shape (6,0)

In [20]:
arr12 = np.arange(18).reshape(6,0)
# missing parameter will not be recalculated by numpy ,autocorrect
arr12

ValueError: cannot reshape array of size 18 into shape (6,0)

## Initial Placeholders

# Zeros

In [22]:
np.zeros(5)
# numpy has separate fuction to create array of only zeros

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros([5,5])
# use [] for entering the dimension values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros([10,10])
# use [] for entering the dimension values

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros([10,10]).reshape(4,25)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Ones

In [31]:
np.ones(5)
# # numpy has separate fuction to create array of only ones

array([1., 1., 1., 1., 1.])

In [33]:
np.ones([5,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# identity matrix

In [34]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(1)

array([[1.]])

# diagonal diag

In [42]:
np.diag([11,22,33])

array([[11,  0,  0],
       [ 0, 22,  0],
       [ 0,  0, 33]])

In [43]:
np.diag([11,22,33,44,55])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [44]:
np.diag([2,4])

array([[2, 0],
       [0, 4]])

In [45]:
np.diag([2])

array([[2]])