## Indexing and Slicing

## with 1D Array

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(5,12)
arr1

array([ 5,  6,  7,  8,  9, 10, 11])

In [6]:
arr1[0]

5

In [7]:
arr1[5]

10

In [8]:
# Slicing
arr1[0:3]

array([5, 6, 7])

In [11]:
arr1[0:6:2]

array([5, 7, 9])

In [12]:
arr1[0:6:3]

array([5, 8])

In [13]:
# support neg indexing
arr1[-1]

11

In [14]:
# array reversal using negative indexing
# revesal in based on index position
arr1[::-1]

array([11, 10,  9,  8,  7,  6,  5])

## with 2D Array

In [15]:
arr2 = np.arange(15).reshape(3,5)

In [16]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr2.ndim

2

In [18]:
arr2[0]
#array[row_number_start:row_number_end]

array([0, 1, 2, 3, 4])

In [19]:
arr2[1]

array([5, 6, 7, 8, 9])

In [20]:
arr2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
arr3 = np.arange(50).reshape(10,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [22]:
arr3[0]

array([0, 1, 2, 3, 4])

In [23]:
arr3[3]

array([15, 16, 17, 18, 19])

In [24]:
arr3[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr3[0:5:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Slicing

In [26]:
# arr1[x][y] arry[rows][columns]

In [27]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [28]:
arr4[0][0]

0

In [29]:
arr4[2][2]

12

In [32]:
arr4[4:6][1:3]
# arr4[4:6]

array([[25, 26, 27, 28, 29]])

In [33]:
# for intersection if rows and columns
# arr1[x][y]
# arry[rows_start:rows_end , columns_start:columns_end]

In [34]:
arr4[4:6,1:3]

array([[21, 22],
       [26, 27]])