In [3]:
import numpy as np

# Indexing with Boolean Arrays

In [4]:
# masking
# boolean indexing

In [5]:
arr1 = np.arange(12).reshape(3,4)

In [6]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr1 + 10
# this is elementwise operation

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [8]:
arr1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [9]:
arr1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
arr1<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [11]:
arr1 % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [12]:
arr1 % 2 != 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [13]:
arr1 % 3 == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [14]:
# multiple conditions

In [16]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# arr1 % 2 == 0
# and
# arr1 % 3 == 0

In [18]:
(arr1 % 2 == 0) & (arr1 % 3 == 0)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [19]:
# arr1 % 2 == 0
# or
# arr1 % 3 == 0

In [23]:
arr2 = (arr1 % 2 == 0)|(arr1 % 3 == 0)

In [24]:
arr2

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [21]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr2
# boolean array? values are boolean

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [26]:
arr1[((arr1 % 2 == 0)|(arr1 % 3 == 0))]
# to get int values put expresion in arr1[]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [27]:
arr1[(arr1>10)]

array([11])

In [28]:
arr1[(arr1 % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

In [29]:
arr1[((arr1 % 2 == 0) & (arr1 % 3 == 0))]

array([0, 6])

# Universal Function

In [30]:
# array must be of same shape and size

In [31]:
# https://numpy.org/doc/stable/user/quickstart.html#universal-functions

In [35]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [36]:
a + 10

array([21, 32, 43, 54, 65])

In [37]:
a

array([11, 22, 33, 44, 55])

In [39]:
a + b

array([12, 24, 36, 48, 60])

In [40]:
a-b

array([10, 20, 30, 40, 50])

In [41]:
a*b

array([ 11,  44,  99, 176, 275])

In [42]:
a/b

array([11., 11., 11., 11., 11.])

In [43]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 0]


In [44]:
a*b

array([ 11,  44,  99, 176,   0])

In [45]:
a/b

C:\Users\admin\AppData\Local\Temp\ipykernel_8444\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([11., 11., 11., 11., inf])

In [46]:
b/a

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.        ])

In [47]:
a = np.array([11,22,33,44,0])
b = np.array([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44  0]
[1 2 3 4 0]


In [48]:
a/b

C:\Users\admin\AppData\Local\Temp\ipykernel_8444\1348051284.py:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([11., 11., 11., 11., nan])

In [49]:
a = np.array([11,22,33,44])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44]
[1 2 3 4 5]


In [52]:
a+b
# array must be of same size and shape

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [51]:
# https://numpy.org/doc/stable/user/quickstart.html#broadcasting-rules

In [53]:
# /HW
# 1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


# 1. 'Priya', 'Rohit', 'Aryan'
# 2. 'Riya','Devanshi'
# 3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
# 4. 'Avni'
# 5. 'Neha'


In [65]:
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])
s

array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']], dtype='<U8')

In [70]:
# 1. = 'Priya', 'Rohit', 'Aryan'
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [71]:
# 2. 'Riya','Devanshi'
s[2][1:3]

array(['Riya', 'Devanshi'], dtype='<U8')

In [74]:
# 3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
s[1][0:3],s[2][0:3]

(array(['Neha', 'Avni', 'Akash'], dtype='<U8'),
 array(['Arjun', 'Riya', 'Devanshi'], dtype='<U8'))

In [73]:
# 4. 'Avni'
s[1,1]

'Avni'

In [69]:
# 5. 'Neha'
s[1,0]

'Neha'

In [75]:
# 2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
# 1. find all scores > 50
# 2. find all scores <35

In [76]:
score = np.random.randint(10,100,15).reshape(5,3)

In [77]:
score

array([[79, 34, 57],
       [22, 42, 66],
       [34, 45, 42],
       [42, 87, 16],
       [11, 97, 76]])

In [79]:
score[score>50]

array([79, 57, 66, 87, 97, 76])

In [80]:
score[score<35]

array([34, 22, 34, 16, 11])

In [81]:
score = np.random.randint(10,100,15).reshape(5,3)
score

array([[25, 54, 41],
       [48, 58, 21],
       [16, 61, 46],
       [23, 71, 83],
       [86, 79, 86]])