# Aggregate Function

In [1]:
# 1D Array

In [2]:
import numpy as np

In [3]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [4]:
a*b

array([ 11,  44,  99, 176, 275])

In [5]:
a+b

array([12, 24, 36, 48, 60])

In [6]:
np.sum(a)
# to calculate sum of array 

165

In [7]:
np.min(a)
# to calculate minimun value of array 

11

In [8]:
np.max(a)
# to calculate maximum value of array

55

In [9]:
np.min(b)

1

In [10]:
np.max(b)

5

In [11]:
np.sum(b)

15

In [12]:
np.mean(a)
# to calculate mean of array i.e avarage

33.0

In [13]:
np.mean(b)

3.0

In [14]:
# 2D Array

In [19]:
arr1 = np.arange(10,60,2).reshape(5,5)

In [20]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [22]:
np.sum(arr1,axis=None)

850

In [23]:
np.sum(arr1)

850

In [24]:
np.sum(arr1,axis=0)
# axis=0 ==> sum of columns
# calcualte sum of each columns in array

array([150, 160, 170, 180, 190])

In [25]:
np.sum(arr1,axis=1)
# axis=1 ==> sum of rows
# calcualte sum of each row in array

array([ 70, 120, 170, 220, 270])

In [26]:
np.max(arr1)

58

In [27]:
np.max(arr1,axis=0)
# max of each column in array

array([50, 52, 54, 56, 58])

In [28]:
np.max(aar1,axis=1)
# max of each row in array

array([18, 28, 38, 48, 58])

In [29]:
np.mean(arr1,axis=1)
# mean of each row in array

array([14., 24., 34., 44., 54.])

In [31]:
score = np.random.randint(10,100,15).reshape(5,3)

In [32]:
score

array([[33, 45, 63],
       [62, 79, 32],
       [83, 63, 49],
       [46, 77, 43],
       [73, 73, 22]])

In [33]:
np.sum(score,axis=0)
# column

array([297, 337, 209])

In [34]:
np.sum(score,axis=1)
# rows

array([141, 173, 195, 166, 168])

In [35]:
np.mean(score,axis=1)
# rows

array([47.        , 57.66666667, 65.        , 55.33333333, 56.        ])

In [36]:
np.min(score,axis=1)

array([33, 32, 49, 43, 22])

In [37]:
np.max(score,axis=0)
# column

array([83, 79, 63])

# Logical Function

In [38]:
# any : all the elements should be zero for o/p to be False : behave like OR
# all : all the elements should be non-zero for o/p to be True : behave like AND
# True and False

In [39]:
score = np.random.randint(10,100,15).reshape(5,3)

In [40]:
score

array([[60, 58, 44],
       [77, 46, 91],
       [31, 61, 57],
       [43, 72, 16],
       [62, 33, 55]])

In [41]:
arr5 = np.array([11,22,33,0,55])

In [42]:
np.any(arr5)

True

In [44]:
arr5 = np.array([0,0,0,0,55])
np.any(arr5)

True

In [45]:
arr5 = np.array([0,0,0,0,0])
np.any(arr5)

False

In [46]:
# all

In [47]:
arr5 = np.array([11,22,33,44,55])
np.all(arr5)

True

In [48]:
arr5 = np.array([1,2,3,4,0])
np.all(arr5)

False

In [ ]:
# https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting