# Broadcasting

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(15).reshape(5,3)

In [3]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
arr2 = np.arange(15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
arr1+arr2
# will not add because of different shapes

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [8]:
x = np.array([10,20,30])
y = np.array([[1],[2],[3],[4]])

In [9]:
x.ndim

1

In [10]:
y.ndim

2

In [12]:
x

array([10, 20, 30])

In [13]:
y

array([[1],
       [2],
       [3],
       [4]])

In [11]:
x+y
# will add array x and y because of broadcasting
# broadcasting means array creates replica in shape which will match another array and performs operation

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [14]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
arr2 = np.array([100,200,300])
arr2

array([100, 200, 300])

In [16]:
arr1+arr2

array([[100, 201, 302],
       [103, 204, 305],
       [106, 207, 308],
       [109, 210, 311],
       [112, 213, 314]])

In [17]:
a = np.arange(10)
b = np.arange(5)

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b

array([0, 1, 2, 3, 4])

In [20]:
a+b

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [27]:
arr3 = np.arange(12).reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr4 = np.arange(4)
arr4

array([0, 1, 2, 3])

In [29]:
arr3+arr4

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [30]:
arr3 = np.arange(12).reshape(4,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
arr4 = np.arange(4)
arr4

array([0, 1, 2, 3])

In [32]:
arr3+arr4

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

# Splitting

### 1D Array

In [33]:
# splitting 1D array
# will split array in no of equal parts

In [34]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.split(x,3)
# will split array x into 3 equal no of array

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [36]:
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.split(z,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [38]:
np.split(z,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [39]:
np.split(z,10)
# not possible to split 10 in equal parts

ValueError: array split does not result in an equal division

In [40]:
np.split(z,12)

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11])]

In [41]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
np.split(z,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [43]:
np.split(z,3)[2]
# accessing the subparts after spliting the array

array([ 8,  9, 10, 11])

In [44]:
np.split(z,4,axis=0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [45]:
np.split(z,4)
# default axis is ZERO

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

### 2D Array

In [46]:
# splitting 2D array
# zero axis = columns
# one axis = rows

In [47]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.split(x,4)
# by default axis = 0 i.e columns

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [54]:
np.split(x,4,axis=0)
# columns
# columns but o/p will be rows because when we split columns we will get rows

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [55]:
np.split(x,4,axis=1)
# axis 1 = rows
# rows but o/p will be columns because when we split rows we will get columns

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [57]:
y = np.arange(18).reshape(6,3)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [58]:
np.split(y,3,axis=0)
# columns
# columns but o/p will be rows because when we split columns we will get rows

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [59]:
np.split(y,3,axis=1)
# rows but o/p will be columns because when we split rows we will get columns

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]